# Generated by Django 4.1.6 on 2023-02-10 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_catagory_alter_products_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
    ]
